apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: openrev-staging
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4050Mi
