---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org1
  namespace: openrev-staging
  labels:
    app: chaincode-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org1
    spec:
      containers:
        - image: oakenknight/openrev-cc:v1.2
          imagePullPolicy: Always
          name: chaincode-basic-org1
          env:
            - name: CHAINCODE_ID
              value: "basic:98ea84a78a3616a989161264a36297ab22abada1a073694b2bf60fd58b418b31"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
